CREATE DATABASE PROVA
GO
USE PROVA
GO


CREATE TABLE CLIENTE
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	CPF CHAR(18),
	RG CHAR(14),
	DATA_NASCIMENTO DATETIME,
	LOGRADOURO VARCHAR(100),
	CEP VARCHAR(12),
	CIDADE VARCHAR(100),
	BAIRRO VARCHAR(100)
)


/* INSERT */
CREATE PROCEDURE INSERIR_CLIENTE
       @NOME AS VARCHAR(100),
       @EMAIL AS VARCHAR (100),
	   @CPF AS VARCHAR(18),
	   @RG AS VARCHAR(14),
       @DATA_NASCIMENTO AS DATETIME,
	   @LOGRADOURO AS VARCHAR(100),
	   @CEP AS VARCHAR(12),
	   @CIDADE AS VARCHAR(100),
	   @BAIRRO AS VARCHAR(100)  
AS
BEGIN
       INSERT INTO CLIENTE (NOME, EMAIL, CPF, RG, DATA_NASCIMENTO, LOGRADOURO, CEP, CIDADE, BAIRRO)
       VALUES (@NOME, @EMAIL, @CPF, @RG, @DATA_NASCIMENTO, @LOGRADOURO, @CEP, @CIDADE, @BAIRRO)
END

/* UPDATE */
CREATE PROCEDURE ATUALIZAR_CLIENTE
       @NOME AS VARCHAR(100),
       @EMAIL AS VARCHAR (100),
	   @CPF AS VARCHAR(18),
	   @RG AS VARCHAR(14),
       @DATA_NASCIMENTO AS DATETIME,
	   @LOGRADOURO AS VARCHAR(100),
	   @CEP AS VARCHAR(12),
	   @CIDADE AS VARCHAR(100),
	   @BAIRRO AS VARCHAR(100)    
AS
BEGIN
       UPDATE CLIENTE SET NOME=@NOME, EMAIL=@EMAIL, CPF=@CPF, RG=@RG, DATA_NASCIMENTO=@DATA_NASCIMENTO, LOGRADOURO=@LOGRADOURO, CEP=@CEP, CIDADE=@CIDADE, BAIRRO=@BAIRRO WHERE ID=@ID
END

/* DELETE */
CREATE PROCEDURE EXCLUIR_CLIENTE
       @ID AS INT
AS
BEGIN
       DELETE FROM CLIENTE WHERE ID=@ID
END

/* SELECT 1 CLIENTE*/
CREATE PROCEDURE SELECIONAR_CLIENTE
       @ID AS INT
AS
BEGIN
       SELECT * FROM CLIENTE WHERE ID=@ID
END

/* SELECT TODOS CLIENTE*/
CREATE PROCEDURE SELECIONAR_CLIENTE       
AS
BEGIN
       SELECT * FROM CLIENTE
END